/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    IconEpAlarmClock: typeof import('~icons/ep/alarm-clock')['default']
    IconEpBaselineAccessTime: typeof import('~icons/ep/baseline-access-time')['default']
    IconHomeCube: typeof import('~icons/home/cube')['default']
    IconIcBaselineAccessTime: typeof import('~icons/ic/baseline-access-time')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
